name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"value1":"test1","value2":"test2","value3":"test3"}' https://maker.ifttt.com/trigger/telegram1234/with/key/cwlBmjg4cNE8S66APBk6j
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
